apiVersion: v1
kind: Secret ## tipo: segredos — tratados com mais cuidado que configmap
metadata:
  name: api-secret    # nome pelo qual os deployments referenciam este secret
  namespace: dev 
type: Opaque # tipo genérico — significa "bytes arbitrários", o mais comum
data:  # valores precisam estar em base64 obrigatoriamente 
  SECRET_KEY: c3VhLXNlY3JldC1rZXktZGV2  # base64 de "dev-secret-key"
  POSTGRES_PASSWORD: QW5uYTE4MjEzNQ==        # base64 de "123456"
  DATABASE_URL: cG9zdGdyZXNxbDovL2FubmE6QW5uYTE4MjEzNUBkYjo1NDMyL3Blb3BsZWRldg==  # base64 de "postgresql://anna:123456@db:5432/peopledev"