apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: prod
type: Opaque
data:
  SECRET_KEY: NTNlN2Q2MjU2ZTM0Y2U3YjJlOTQwY2E2YTk1OGMwMGFjNWVmYTFkZDQwODEwZTk5ZmU3YTc2YTU3NDMzMDg4Yg==
  POSTGRES_PASSWORD: QW5uYTE4MjEzNQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL2FubmE6QW5uYTE4MjEzNUBkYjo1NDMyL3Blb3BsZXByb2Q=